import {StyleSheet, I18nManager, Platform, Dimensions} from 'react-native';
import * as Constant from '../constants/globalConstant';
I18nManager.forceRTL(false);

export default StyleSheet.create({
  // Global
  globalContainer: {
    flex: 1,
  },
  rowView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardView: {
    padding: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 20,
    marginVertical: 7,
    backgroundColor: Constant.whiteColor,
  },
  cardMainText: {
    fontSize: 18,
    lineHeight: 26,
    marginHorizontal: 15,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginBottom: 5,
  },
  subCardView: {
    padding: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: '#FCFCFC',
  },
  inputHeading: {
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginTop: 10,
    marginBottom: 5,
  },
  uploadFileView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderStyle: 'dashed',
    paddingHorizontal: 10,
    paddingVertical: 15,
    marginBottom: 10,
    marginTop: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  uploadFileImage: {
    width: 60,
    height: 60,
    marginTop: 10,
  },
  uploadFileViewText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.blueColor,
    marginTop: 10,
    marginBottom: 5,
  },
  smallButton: {
    flexDirection: 'row',
    width: '48%',
    height: 45,
    padding: 10,
    marginTop: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Constant.borderColor,
    justifyContent: 'center',
    borderRadius: 10,
  },
  saveButtonDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  multilineTextInputView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 10,
    height: 150,
    backgroundColor: Constant.whiteColor,
  },
  multilineTextInput: {
    backgroundColor: Constant.whiteColor,
    paddingHorizontal: 10,
    fontSize: 17,
    color: Constant.fontColor,
    fontFamily: Constant.primaryFontRegular,
  },

  // Header
  headerMainView: {
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    // borderBottomRightRadius: 15,
    // borderBottomLeftRadius: 15,
    borderBottomColor: Constant.borderColor,
    borderLeftColor: Constant.borderColor,
    borderRightColor: Constant.borderColor,
    borderTopColor: Constant.whiteColor,
    borderWidth: 1,
  },
  headerMainDetailView: {
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    backgroundColor: Constant.whiteColor,
    borderBottomColor: Constant.borderColor,
    borderLeftColor: Constant.borderColor,
    borderRightColor: Constant.borderColor,
    borderTopColor: Constant.whiteColor,
    borderWidth: 1,
  },
  headerMainSearchView: {
    backgroundColor: Constant.grayColor,
    height: 40,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    flexDirection: 'row',
    borderRadius: 20,
    paddingHorizontal: 20,
    width: '60%',
    alignItems: 'center',
  },
  headerDrawerIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 60,
    backgroundColor: Constant.grayColor,
  },
  headerPhoto: {
    width: 45,
    height: 45,
    borderRadius: 45 / 2,
  },
  // FormButton
  buttonContainer: {
    flexDirection: 'row',
    width: '100%',
    // height: 45,
    padding: 10,
    marginVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 1,
  },
  buttonText: {
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 26,
    fontFamily: Constant.primaryFontSemiBold,
  },

  // FormInput
  inputContainer: {
    marginTop: 5,
    marginBottom: 10,
    width: '100%',
    height: 50,
    // height: Dimensions.get('window').height / 18,
    borderColor: Constant.borderColor,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Constant.whiteColor,
    justifyContent: 'space-between',
  },
  iconStyle: {
    height: '100%',
    width: '10%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  input: {
    backgroundColor: Constant.whiteColor,
    marginLeft: 2,
    borderRadius: 6,
    paddingHorizontal: 10,
    fontSize: 17,
    color: '#062347',
    fontFamily: Constant.primaryFontRegular,
    width: '90%',
    height: '90%',
    
  },

  // imageCarousel
  imageCarouselView: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  imageCarouselImage: {
    width: '100%',
    borderRadius: 10,
    height: 180,
    alignSelf: 'flex-end',
  },

  //CustomCheck
  CustomCheckOuterView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 5,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  CustomCheckInnerView: {
    backgroundColor: Constant.whiteColor,
    padding: 5,
    borderRadius: 20,
  },

  //RBSheet
  RBSheetMainView: {
    backgroundColor: Constant.whiteColor,
    padding: 10,
    flex: 1,
    borderRadius: 10,
  },
  RBSheetHeaderView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  RBSheetHeaderCrossView: {
    height: 45,
    width: 45,
    borderRadius: 45 / 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Constant.grayColor,
  },
  // CheckBox
  checkBoxMainView: {
    flexDirection: 'row',
    paddingVertical: 5,
    marginVertical: 5,
    alignItems: 'center',
  },
  checkBoxCheck: {
    width: 20,
    height: 20,
    backgroundColor: Constant.greenColor,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxUncheck: {
    width: 20,
    height: 20,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: Constant.whiteColor,
  },
  checkBoxText: {
    fontSize: 16,
    fontFamily: Constant.secondryFontBold,
    marginLeft: 15,
    color: Constant.fontColor,
  },
  checkBoxTextSearch: {
    fontSize: 16,
    fontFamily: Constant.secondryFontRegular,
    marginLeft: 15,
    color: Constant.fontColor,
  },

  // Multiselect
  MultiselectmainView: {
    marginVertical: 5,
    backgroundColor: Constant.whiteColor,
    borderColor: Constant.borderColor,
    borderRadius: 10,
  },

  //JoinCommunity
  JoinCommunityMain: {
    backgroundColor: Constant.whiteColor,
    borderRadius: 20,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 15,
    marginVertical: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 0.8},
    shadowOpacity: 0.1,
    shadowRadius: 1,
    alignItems: 'center',
  },
  JoinCommunityText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginVertical: 10,
  },
  JoinCommunityDescription: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    textAlign: 'center',
  },

  // Custom Tab Bar Style
  customTabBarMainContainer: {
    height: 60,
    backgroundColor: Constant.whiteColor,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    borderTopColor: Constant.borderColor,
    borderLeftWidth: 1,
    borderLeftColor: Constant.borderColor,
    borderRightWidth: 1,
    borderRightColor: Constant.borderColor,
    flexDirection: 'row',
    paddingHorizontal: 10,
    width: '100%',
  },
  tabButtonParentStyle: {
    width: '19%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonSelectedBar: {
    width: 25,
    height: 4,
    marginBottom: 8,
    borderBottomRightRadius: 6,
    borderBottomLeftRadius: 6,
  },
  tabButtonTextStyle: {
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: Constant.lightGrayColor,
    fontFamily: Constant.primaryFontBold,
    marginBottom: 5,
  },
  tabSearchButtonParentStyle: {
    width: '24%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabSearchLinearParentStyle: {
    marginTop: -37,
    width: 70,
    height: 70,
    borderRadius: 70 / 2,
    backgroundColor: '#FA475350',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabSearchLinearStyle: {
    width: 60,
    height: 60,
    borderRadius: 60 / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },

  //auth
  LoginKeyboardAvoid: {
    elevation: 3,
    flex: 1,
    shadowOffset: {width: 0, height: 1},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
  },
  skipButtonView: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    marginHorizontal: 5,
    marginTop: 10,
  },
  LoginSkipText: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: Constant.whiteColor,
    fontFamily: Constant.secondryFontRegular,
    marginLeft: 10,
  },
  authFormMainView: {
    width: '100%',
    paddingHorizontal: 15,
    position: 'absolute',
    bottom: 0,
  },
  authFormInsideView: {
    backgroundColor: Constant.whiteColor,
    paddingVertical: 15,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  authFormHeaderView: {
    width: '100%',
    borderBottomColor: Constant.borderColor,
    borderColor: Constant.whiteColor,
    borderWidth: 1,
    paddingHorizontal: 15,
  },
  authFormHeaderText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.primaryFontBold,
    marginTop: 8,
    marginBottom: 15,
  },
  authFormBodyInputs: {
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  authFormBodyInputsHeading: {
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.primaryFontSemiBold,
  },
  authFormFooterView: {
    width: '100%',
    borderTopColor: Constant.borderColor,
    borderColor: Constant.whiteColor,
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 20,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  authFormFooterText: {
    fontFamily: Constant.primaryFontSemiBold,
    fontSize: 18,
    color: Constant.lightGrayColor,
  },
  signupFormMainView: {
    width: '100%',
    paddingHorizontal: 15,
    position: 'absolute',
    bottom: 0,
  },
  signupFormInsideView: {
    backgroundColor: Constant.whiteColor,
    paddingVertical: 15,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  signupFormUserTypeView: {
    width: '100%',
    paddingVertical: 10,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  signupFormUserTypeSingle: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    width: '48%',
    borderRadius: 6,
  },
  signupFormUserTypeSingleText: {
    fontFamily: Constant.primaryFontSemiBold,
    fontSize: 16,
  },
  signupTermsAndConditionText: {
    fontSize: 15,
    fontFamily: Constant.secondryFontRegular,
    marginLeft: 10,
    color: Constant.fontColor,
  },
  signupTermsAndConditionTextLast: {
    fontSize: 15,
    fontFamily: Constant.secondryFontRegular,
    marginLeft: 10,
    color: Constant.blueColor,
  },

  // EmployerCard.js
  employerCardMainView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginHorizontal: 15,
    marginVertical: 5,
    overflow: 'hidden',
    backgroundColor: Constant.whiteColor,
    padding: 15,
  },
  employerCardMainViewNoBorder: {
    marginHorizontal: 5,
    marginVertical: 5,
    overflow: 'hidden',
    backgroundColor: Constant.whiteColor,
    padding: 10,
  },
  employerCardprofileImage: {
    width: 55,
    height: 55,
  },
  employerCardNameView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  employerCardNameText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: Constant.blueColor,
    marginRight: 5,
    fontFamily: Constant.primaryFontRegular,
  },
  employerCardHeadingText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.primaryFontSemiBold,
    marginBottom: 10,
  },
  employerCardFollowerListView: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 10,
    justifyContent: 'space-between',
  },
  employerCardFollowerListSection: {
    // width: '57%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  employerCardFollowerListImagesView: {
    backgroundColor: Constant.whiteColor,
    height: 35,
    width: 35,
    borderRadius: 35 / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  employerCardFollowerListImage: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
  },
  employerCardFollowerText: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.secondryFontRegular,
    marginLeft: 5,
  },
  employerCardButtonFollow: {
    alignItems: 'center',
    borderRadius: 20,
    alignSelf: 'center',
    justifyContent: 'center',
    paddingVertical: 7,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingHorizontal: 10,
  },
  employerCardButtonFollowing: {
    alignItems: 'center',
    borderRadius: 20,
    alignSelf: 'center',
    backgroundColor: Constant.blueColor,
    justifyContent: 'center',
    paddingVertical: 7,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingHorizontal: 10,
  },
  employerCardFollowText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.primaryFontSemiBold,
  },
  employerCardFollowingText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: Constant.whiteColor,
    fontFamily: Constant.primaryFontSemiBold,
  },

  // JobCard.js
  jobCardMainView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginHorizontal: 15,
    marginVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: Constant.whiteColor,
  },
  jobCardMainViewBookmark: {
    marginTop: -2,
    alignSelf: 'flex-end',
  },
  jobCardNameView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  jobCardNameViewText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: Constant.blueColor,
    marginRight: 5,
    fontFamily: Constant.primaryFontRegular,
  },
  jobCardMainHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.primaryFontSemiBold,
    marginBottom: 10,
  },
  jobCardInfoListMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  jobCardInfoListImage: {
    width: 24,
    height: 24,
  },
  jobCardInfoListHeading: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.secondryFontRegular,
    marginLeft: 10,
  },
  jobCardInfoListHeadingValue: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.secondryFontSemiBold,
  },
  jobCardRateText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.secondryFontRegular,
  },
  jobCardRateTextBold: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    fontFamily: Constant.secondryFontSemiBold,
  },
  jobCardRateTextValue: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: Constant.blueColor,
    fontFamily: Constant.primaryFontRegular,
  },

  // Home page style

  homeStartExploringParentStyle: {
    backgroundColor: Constant.whiteColor,
    borderRadius: 20,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 15,
    elevation: 3,
    shadowOffset: {width: 0, height: 1},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    marginTop: 15,
  },
  homeHeadingStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
  },
  homeFreelancerParentStyle: {
    marginVertical: 10,
    backgroundColor: '#6366F1',
    paddingHorizontal: 15,
    paddingVertical: 25,
    borderRadius: 5,
  },
  submitProposalStyle: {
    marginVertical: 5,
    backgroundColor: Constant.primaryColor,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  homeFreelancerHeadingParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  homeFreelancerHeadingTextStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontMedium,
    color: Constant.whiteColor,
  },
  homeFreelancerTaglineTextStyle: {
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontMedium,
    color: Constant.whiteColor,
  },
  homeImageStyle: {width: 50, height: 50},
  homeButtonsParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  homeJobButtonParentStyle: {
    backgroundColor: '#C2549D',
    paddingHorizontal: 15,
    paddingVertical: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    width: '32%',
  },
  homeJobTextStyle: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontMedium,
    color: Constant.whiteColor,
    marginTop: 10,
  },
  homeEmployerParentStyle: {
    backgroundColor: '#FC8370',
    paddingHorizontal: 15,
    paddingVertical: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    width: '32%',
  },
  homeEmployerButtonStyle: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontMedium,
    color: Constant.whiteColor,
    marginTop: 10,
  },
  homeServicesParentStyle: {
    backgroundColor: '#F9BF20',
    paddingHorizontal: 15,
    paddingVertical: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    width: '32%',
  },
  homeServiceTextStyle: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontMedium,
    color: Constant.whiteColor,
    marginTop: 10,
  },
  homeJobCategoryParentStyle: {
    backgroundColor: Constant.whiteColor,
    borderRadius: 20,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 15,
    marginVertical: 10,
    elevation: 3,
    shadowOffset: {width: 0, height: 1},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    alignItems: 'flex-start',
  },
  homeServiceCategoriesParentStyle: {
    backgroundColor: Constant.whiteColor,
    borderRadius: 20,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 15,
    marginVertical: 10,
    elevation: 3,
    shadowOffset: {width: 0, height: 1},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    alignItems: 'flex-start',
  },
  homeServiceProviderCardParentStyle: {
    backgroundColor: Constant.whiteColor,
    borderRadius: 20,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 15,
    marginVertical: 10,
    elevation: 3,
    shadowOffset: {width: 0, height: 1},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    alignItems: 'flex-start',
  },
  homeServicesCardParentStyle: {
    backgroundColor: Constant.whiteColor,
    borderRadius: 20,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 15,
    marginVertical: 10,
    elevation: 3,
    shadowOffset: {width: 0, height: 1},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    alignItems: 'flex-start',
  },
  homeJobbyCountryCardParentStyle: {
    backgroundColor: Constant.whiteColor,
    borderRadius: 20,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 15,
    marginVertical: 10,
    elevation: 3,
    shadowOffset: {width: 0, height: 1},
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    alignItems: 'flex-start',
  },
  // Jobs by country card
  jobByCountryCardParentStyle: {
    borderRadius: 10,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 10,
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 15,
    paddingVertical: 20,
    marginRight: 10,
  },
  jobbyCountryCardImageStyle: {width: 50, height: 50},
  jobByCountryCardTeztStyle: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginTop: 10,
  },
  jobByCountryCardlistingCountTextStyle: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginLeft: 5,
  },

  // Job category card
  jobCatCardParent: {
    flexDirection: 'row',
    borderRadius: 40,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 10,
    marginTop: 10,
    marginRight: 10,
  },
  jobCatCardImageParentCard: {
    width: 50,
    height: 50,
    borderRadius: 50 / 2,
    backgroundColor: '#E3F2FD',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  jobCatCardImageStyle: {width: 26, height: 26, borderRadius: 26 / 2},
  jobCatCardTextStyle: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontMedium,
    color: Constant.fontColor,
    marginTop: 10,
  },

  // Service category card
  serviceCatCardParentStyle: {
    width: 220,
    height: 250,
    marginTop: 10,
    marginRight: 10,
  },
  serviceCatCardGradientStyle: {
    flex: 1,
    borderRadius: 10,
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
  },
  serviceCatCardcountParentStyle: {
    backgroundColor: Constant.primaryColor,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  serviceCatCardCountTextStyle: {
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.whiteColor,
  },
  seviceCatcardtextStyle: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.whiteColor,
  },

  // Service provider card

  ServiceProviderCardPrentStyle: {
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
    borderRadius: 20,
    marginTop: 10,
    paddingHorizontal: 15,
    paddingBottom: 10,
    marginRight: 10,
  },
  ServiceProviderCardNameParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  serviceProviderCarImageStyle: {
    width: 43,
    height: 43,
    borderRadius: 43 / 2,
    marginRight: 10,
  },
  ServiceProviderCardNameTextStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginRight: 5,
  },
  ServiceProviderCardTaglineStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginRight: 5,
    marginBottom: 5,
    paddingBottom: 5,
  },
  serviceProviderRatingTextStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontSemiBold,
    color: Constant.fontColor,
    marginLeft: 5,
  },
  ServiceProviderCardReviewCountStyle: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginLeft: 5,
  },
  ServiceProviderCardLocationParentStyle: {
    flexDirection: 'row',
    marginVertical: 5,
    alignItems: 'center',
  },
  serviceProviderLocationImageStyle: {
    width: 24,
    height: 24,
    borderRadius: 24 / 2,
  },
  serviceProviderLocationTextStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontSemiBold,
    color: '#484848',
    marginLeft: 5,
  },
  serviceProviderPriceParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
  },
  serviceProviderStartingPriceTextStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginLeft: 5,
  },
  serviceProviderPriceTextStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.blueColor,
    marginLeft: 5,
  },

  // Service list card
  serviceListCardParentStyle: {
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
    borderRadius: 10,
    marginTop: 10,
    marginRight: 10,
  },
  serviceListImageBackgeoundStyle: {
    height: 150,
  },
  serviceListCardImagebackgroundOverlyStyle: {
    flex: 1,
    backgroundColor: '#00000040',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  serviceListCardImageParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  servisListImageParentStyle: {
    backgroundColor: Constant.whiteColor,
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -25,
  },
  serviceListImageStyle: {
    width: 43,
    height: 43,
    borderRadius: 43 / 2,
  },
  serviceListCardNameParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  serviceListCardNameStyle: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.blueColor,
    marginRight: 5,
  },
  serviceListCardTaglineStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginRight: 5,
    paddingHorizontal: 10,
    paddingBottom: 5,
  },
  serviceListCardReviewParentStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  serviceListCardratingTextStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontBold,
    color: Constant.fontColor,
    marginLeft: 5,
  },
  serviceListCardRatingCountStyle: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginLeft: 5,
  },
  serviceListViewstestStyle: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginLeft: 5,
  },
  serviceListCardPriceParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  serviceListStartingFromTestStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginLeft: 5,
  },
  serviceListPriceTextStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.blueColor,
    marginLeft: 5,
  },

  // FreelancerDetail.js
  freelancerDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  freelancerDetailTopTabView: {
    paddingHorizontal: 15,
    paddingVertical: 15,
    backgroundColor: Constant.whiteColor,
  },
  freelancerDetailTopTabViewSingle: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 8,
  },
  freelancerDetailTopTabViewSingleText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
  },
  freelancerDetailCardName: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  freelancerDetailCardImageStyle: {
    width: 46,
    height: 46,
    borderRadius: 46 / 2,
    marginRight: 10,
  },
  freelancerDetailCardNameTextStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginRight: 5,
  },
  freelancerDetailPriceTextStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.blueColor,
    marginLeft: 5,
  },
  freelancerDetailCardTaglineStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginRight: 5,
    marginBottom: 5,
    paddingBottom: 5,
  },
  freelancerDetailCardReviewView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  freelancerDetailPriceParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
  },
  freelancerDetailRatingTextStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontSemiBold,
    color: Constant.fontColor,
    marginLeft: 5,
  },
  freelancerDetailValuesTextStyle: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: '#484848',
    marginLeft: 5,
  },
  freelancerDetailLocationParentStyle: {
    flexDirection: 'row',
    marginVertical: 5,
    alignItems: 'center',
  },
  freelancerDetailLocationImageStyle: {
    width: 24,
    height: 24,
    borderRadius: 24 / 2,
  },
  freelancerDetailLocationTextStyle: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontSemiBold,
    color: '#484848',
    marginLeft: 5,
  },
  freelancerDetailShowButton: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontMedium,
    color: Constant.blueColor,
    alignSelf: 'center',
    marginBottom: 10,
  },
  freelancerDetailCardMainView: {
    padding: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: Constant.whiteColor,
  },
  freelancerDetailCardMainViewMiddle: {
    padding: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: Constant.whiteColor,
  },
  freelancerDetailCardMainHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  freelancerDetailCardMainHeadingBold: {
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  freelancerDetailSkillText: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginTop: 5,
    fontFamily: Constant.primaryFontMedium,
    color: Constant.fontColor,
  },
  freelancerDetailSkillPercentage: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  freelancerDetailCountingView: {
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: Constant.whiteColor,
  },
  freelancerDetailCountingSingleView: {
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
    width: '50%',
    paddingVertical: 20,
  },
  freelancerDetailCountingSingleViewLast: {
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
    width: '100%',
    paddingVertical: 20,
  },
  freelancerDetailCountingTextValue: {
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
  },
  freelancerDetailCountingTextHeading: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginTop: 5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.fontColor,
  },
  freelancerDetailCraftedMainView: {
    width: 200,
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
    borderRadius: 10,
    marginTop: 10,
    marginRight: 10,
  },
  freelancerDetailImageOverly: {
    flex: 1,
    backgroundColor: '#00000040',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  freelancerDetailCraftedTextView: {
    marginHorizontal: 10,
    marginVertical: 15,
  },
  freelancerDetailCraftedTextHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  freelancerDetailCraftedTextLink: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: '#484848',
  },
  freelancerDetailPortfolioMainView: {
    width: 280,
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
    borderRadius: 10,
    marginTop: 10,
    marginRight: 10,
  },
  freelancerDetailPortfolioProfileView: {
    backgroundColor: Constant.whiteColor,
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -27,
    marginLeft: 10,
  },
  freelancerDetailPortfolioImageStyle: {
    width: 43,
    height: 43,
    borderRadius: 43 / 2,
  },
  freelancerDetailPortfolioTextView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 10,
  },
  freelancerDetailPortfolioTextName: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.blueColor,
    marginRight: 5,
  },
  freelancerDetailPortfolioTextTagline: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginRight: 5,
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  freelancerDetailEduMainView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 15,
    marginVertical: 5,
    borderRadius: 6,
  },
  freelancerDetailEduExpMTextValue: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontMedium,
    color: '#484848',
    marginRight: 5,
    paddingHorizontal: 10,
  },
  freelancerDetailEduExpTextHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginRight: 5,
    paddingBottom: 5,
  },
  freelancerDetailEduExpTextDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontMedium,
    color: Constant.fontColor,
  },
  freelancerDetailAwardsView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 15,
    marginVertical: 5,
    borderRadius: 10,
  },
  freelancerDetailAwardsImage: {
    width: 55,
    height: 55,
  },
  freelancerDetailAwardsMainText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    paddingHorizontal: 10,
  },
  freelancerDetailAwardsDateText: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontMedium,
    color: '#484848',
    paddingHorizontal: 10,
  },
  freelancerDetailFAQsMainHeading: {
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  freelancerDetailFAQsFlatlist: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 6,
  },
  freelancerDetailFAQsQuestionView: {
    width: '100%',
    backgroundColor: Constant.grayColor,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 20,
    borderBottomColor: Constant.borderColor,
  },
  freelancerDetailFAQsQuestionText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    width: '90%',
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  freelancerDetailFAQsAnswerView: {
    backgroundColor: Constant.whiteColor,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  freelancerDetailFAQsAnswerText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },

  //JobDetail.js
  JobDetailHeading: {
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginRight: 5,
    marginBottom: 10,
  },
  JobDetailCardMainView: {
    padding: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: Constant.whiteColor,
  },
  JobDetailCardMainText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  JobDetailCardMainTextSub: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginBottom: 5,
  },
  JobDetailCardDescription: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginBottom: 10,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  JobDetailItemView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    marginRight: 10,
    marginVertical: 5,
  },
  JobDetailItemText: {
    fontFamily: Constant.primaryFontMedium,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    padding: 5,
  },
  JobDetailAttachmentItemView: {
    backgroundColor: '#FCFCFC',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  JobDetailAttachmentItemText: {
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.5,
    width: '82%',
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  JobDetailFAQsMainHeading: {
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  JobDetailFAQsFlatlist: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 6,
  },
  JobDetailFAQsQuestionView: {
    width: '100%',
    backgroundColor: Constant.grayColor,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 20,
    borderBottomColor: Constant.borderColor,
  },
  JobDetailFAQsQuestionText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    width: '90%',
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  JobDetailFAQsAnswerView: {
    backgroundColor: Constant.whiteColor,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  JobDetailFAQsAnswerText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  JobDetailEmployerView: {
    paddingVertical: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: Constant.whiteColor,
  },
  JobDetailEmployerText: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    paddingHorizontal: 15,
    marginBottom: 5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
  },

  //EmployerDetail
  EmployerDetailMainTopView: {
    width: '100%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    backgroundColor: Constant.whiteColor,
    marginRight: 10,
  },
  EmployerDetailTopImageOverly: {
    flex: 1,
    backgroundColor: '#00000040',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  EmployerDetailMainCardView: {
    padding: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginVertical: 10,
    backgroundColor: Constant.whiteColor,
  },
  EmployerDetailMainCardText: {
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  EmployerDetailMainCardDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginBottom: 10,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  EmployerDetailProjectView: {
    paddingHorizontal: 10,
    borderRadius: 10,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingVertical: 15,
    marginBottom: 10,
  },
  EmployerDetailProjectUserName: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.blueColor,
    marginRight: 5,
  },
  EmployerDetailProjectName: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginRight: 5,
  },
  EmployerDetailProjectStartText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginRight: 5,
    marginBottom: 10,
  },
  EmployerDetailProjectPrice: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.blueColor,
  },
  EmployerDetailProjectDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginBottom: 10,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  EmployerDetailProjectSkillView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    marginRight: 10,
    marginVertical: 5,
  },
  EmployerDetailProjectSkillText: {
    fontFamily: Constant.primaryFontMedium,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    padding: 5,
  },

  // Drawer style
  drawerItemParentStyle: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    paddingBottom: 5,
    marginTop: 10,
  },
  drawerItemTextStyle: {
    fontFamily: Constant.primaryFontRegular,
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: Constant.fontColor,
    marginLeft: 15,
  },
  drawerImageBackgeoundStyle: {
    width: '100%',
    height: 220,
  },
  drawerHeaderParentContentStyle: {
    backgroundColor: '#00000095',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  drawerNameStyle: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.whiteColor,
    marginRight: 5,
    marginTop: 10,
  },
  drawerPostButtonStyle: {
    backgroundColor: Constant.primaryColor,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    width: '100%',
    padding: 7,
    marginTop: 5,
  },
  drawerPostButtonTextStyle: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.whiteColor,
    marginRight: 5,
  },
  drawerAddonStyle: {
    borderBottomWidth: 1,
    alignItems: 'center',
    borderBottomColor: '#eee',
  },
  drawerAddonParentStyle: {
    borderBottomWidth: 1,
    flexDirection: 'column',
    borderBottomColor: '#eee',
  },
  drawerDropdownItemParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  drawerChildItemAddonStyle: {
    alignItems: 'center',
    paddingHorizontal: 6,
    marginTop: 0,
  },

  // Service detail style
  serviceDetailCatTextStyle: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    marginRight: 5,
    color: Constant.blueColor,
  },
  serviceDetailTitleStyle: {
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
  },
  serviceDetailContentItemParentStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  serviceDetailDescParentStyle: {
    width: '100%',
    backgroundColor: Constant.whiteColor,
    paddingTop: 10,
  },
  serviceDetailDescTitleStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
  },
  serviceDetailDescAddonStyle: {color: Constant.fontColor, marginLeft: 0},
  serviceDetailAboutParentStyle: {
    width: '100%',
    backgroundColor: Constant.whiteColor,
    paddingTop: 10,
  },
  serviceDetailAboutSellerTextStyle: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
  },
  serviceDetailAboutSectionParentStyle: {
    borderRadius: 10,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 10,
    marginTop: 5,
    backgroundColor: Constant.whiteColor,
  },
  serviceDetailSeparatorStyle: {
    borderBottomColor: Constant.borderColor,
    borderBottomWidth: 1,
  },
  servcieDetailAddonCardParentStyle: {
    borderRadius: 5,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    padding: 15,
    marginTop: 5,
    backgroundColor: '#FCFCFC',
    flexDirection: 'row',
  },
  serviceDetailAddonCardTitleStyle: {
    marginLeft: 0,
    color: Constant.fontColor,
    fontSize: 15,
  },
  serviceDetailAddonCardDescStyle: {marginLeft: 0, color: '#676767'},
  serviceDetailBottomTextStyle: {
    marginLeft: 0,
    color: '#676767',
    textAlign: 'center',
  },

  // PricePlan.js
  pricePlanMainView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 20,
  },
  pricePlanName: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
  },
  pricePlanNameDesc: {
    fontSize: 15,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  pricePlanPriceView: {
    alignItems: 'center',
    justifyContent: 'center',
    borderTopColor: Constant.borderColor,
    borderTopWidth: 1,
    borderBottomColor: Constant.borderColor,
    borderBottomWidth: 1,
    backgroundColor: Constant.grayColor,
    paddingVertical: 15,
    marginVertical: 10,
  },
  pricePlanPriceText: {
    fontSize: 28,
    lineHeight: 38,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
  },
  pricePlanPriceDurationText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  pricePlanOptionView: {
    paddingHorizontal: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pricePlanOptionName: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  pricePlanOptionValue: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontSemiBold,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  pricePlanHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  pricePlanDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginBottom: 10,
  },

  // IdentityVerification.js
  identityVerificationHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  identityVerificationDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginBottom: 20,
  },
  identityVerificationSaveView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 15,
    marginVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  identityVerificationSaveDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginBottom: 20,
    textAlign: 'center',
  },

  //PostService.js
  PostServiceListView: {
    borderRadius: 5,
    borderColor: '#dddddd',
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingBottom: 15,
    paddingTop: 5,
    marginTop: 5,
    backgroundColor: '#FCFCFC',
    flexDirection: 'row',
  },
  PostServiceListText: {
    marginLeft: 10,
    fontSize: 15,
    marginTop: 5,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  PostServiceListPriceText: {
    fontFamily: Constant.primaryFontRegular,
    marginLeft: 10,
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    color: Constant.blueColor,
  },
  PostServiceImageUploadDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  PostServiceSaveDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginBottom: 10,
  },

  //ProfileSetting
  profileSettingImageView: {
    width: '100%',
    // borderColor: Constant.borderColor,
    // borderWidth: 1,
    borderRadius: 10,
    marginVertical: 10,
    marginRight: 10,
    marginBottom: 20,
  },
  profileSettingImageDetailView: {
    marginHorizontal: 10,
    marginVertical: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  profileSettingSkillPercentage: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.fontColor,
  },
  profileSettingExpDesc: {
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginTop: 10,
    marginBottom: 5,
  },
  profileSettingProjectView: {
    paddingHorizontal: 10,
    borderColor: Constant.borderColor,
    borderBottomColor: Constant.whiteColor,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderWidth: 1,
    paddingVertical: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 10,
  },
  profileSettingProjectViewImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  profileSettingProjectName: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: '#484848',
    marginBottom: 5,
  },
  profileSettingProjectLink: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.blueColor,
  },
  profileSettingProjectListView: {
    paddingHorizontal: 10,
    borderColor: Constant.borderColor,
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 10,
  },
  profileSettingFAQList: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: '#484848',
    marginBottom: 5,
    width: '90%',
  },

  //PayoutSettings.js
  PayoutSettingsWithdrawView: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    backgroundColor: '#C2549D',
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 15,
  },
  PayoutSettingsWithdrawImage: {
    width: 60,
    height: 60,
    marginVertical: 10,
  },
  PayoutSettingsWithdrawAmount: {
    fontSize: 28,
    lineHeight: 38,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontBold,
    color: Constant.whiteColor,
  },
  PayoutSettingsWithdrawBalance: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.whiteColor,
  },
  PayoutSettingsPayoutView: {
    backgroundColor: '#FCFCFC',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
  },
  PayoutSettingsPayoutViewTop: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  PayoutSettingsPayoutImage: {
    width: 80,
    height: 30,
    marginHorizontal: 10,
  },
  PayoutSettingsPayoutName: {
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  PayoutSettingsPayoutDesc: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  PayoutSettingsPayoutAccountLink: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.blueColor,
  },
  PayoutSettingsPayoutListView: {
    borderColor: Constant.borderColor,
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 10,
    backgroundColor: '#FCFCFC',
  },
  PayoutSettingsPayoutListSection: {
    borderBottomColor: Constant.borderColor,
    borderBottomWidth: 1,
    paddingVertical: 15,
  },
  PayoutSettingsPayoutListHeading: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    paddingHorizontal: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  PayoutSettingsPayoutListValue: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    paddingHorizontal: 15,
    fontFamily: Constant.primaryFontRegular,
    color: '#484848',
  },

  // ManagePortfolio
  managePortfolioImagesDesc: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontMedium,
    color: Constant.fontColor,
    marginBottom: 10,
  },
  managePortfolioSearchView: {
    backgroundColor: Constant.grayColor,
    height: 40,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    flexDirection: 'row',
    borderRadius: 20,
    paddingHorizontal: 20,
    width: '100%',
    marginVertical: 5,
    alignItems: 'center',
  },
  managePortfolioListView: {
    borderColor: Constant.borderColor,
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginTop: 10,
    borderBottomColor: Constant.whiteColor,
  },
  managePortfolioListTopView: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
  },
  managePortfolioListImage: {
    width: 55,
    height: 55,
    borderRadius: 6,
  },
  managePortfolioListHeading: {
    fontSize: 18,
    lineHeight: 26,
    width: '70%',
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  managePostedServiceListBottomView: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  managePortfolioListBottomView: {
    width: '100%',
    justifyContent: 'space-between',
    backgroundColor: Constant.whiteColor,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomLeftRadius: 10,
    borderRadius: 0,
    borderBottomRightRadius: 10,
  },
  managePortfolioListDropDown: {
    backgroundColor: Constant.whiteColor,
    borderColor: Constant.borderColor,
    borderBottomLeftRadius: 10,
    borderRadius: 0,
    width: '100%',
  },
  managePortfolioListStatus: {
    backgroundColor: Constant.greenColor,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomRightRadius: 10,
    marginLeft: -5,
    width: '14%',
    height: 50,
  },

  // ProjectProposalCard.js
  projectProposalCardView: {
    padding: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomColor: Constant.whiteColor,
    marginTop: 10,
    alignItems: 'flex-start',
  },
  projectProposalCardStatus: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
  },
  projectProposalCardStatusText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.whiteColor,
  },
  projectProposalCardHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginTop: 10,
  },
  projectProposalCardTag: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: '#484848',
    marginBottom: 5,
  },
  projectProposalCardPrice: {
    fontSize: 22,
    lineHeight: 30,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
    marginTop: 10,
  },
  projectProposalCardLeftButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomLeftRadius: 10,
  },
  projectProposalCardRightButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomRightRadius: 10,
    backgroundColor: Constant.grayColor,
    borderLeftColor: Constant.whiteColor,
  },

  // ProjectStatusCard.js
  projectStatusCardView: {
    padding: 15,
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
  },
  projectStatusCardStatus: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    marginBottom: 10,
    backgroundColor: Constant.greenColor,
  },
  projectStatusCardStatusText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.whiteColor,
  },

  // QouteCard.js
  qouteCardViewTile: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
    alignItems: 'center',
  },
  qouteCardViewTileBottom: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 10,
  },
  qouteCardViewTileImage: {
    width: 55,
    height: 55,
    borderRadius: 55 / 2,
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
  },
  qouteCardViewTileHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  qouteCardViewTilePriceText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  qouteCardViewTilePriceValue: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.blueColor,
  },
  qouteCardSeparatorView: {
    width: '15%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  separatorViewUper: {
    borderLeftColor: '#00000040',
    borderLeftWidth: 1,
    height: 10,
    marginBottom: 5,
  },
  separatorViewBottom: {
    borderLeftColor: '#00000040',
    borderLeftWidth: 1,
    height: 10,
    marginTop: 5,
  },
  qouteCardLeftButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomLeftRadius: 10,
    backgroundColor: Constant.grayColor,
  },
  qouteCardRightButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomRightRadius: 10,
    backgroundColor: Constant.primaryColor,
    borderLeftColor: Constant.whiteColor,
  },
  qouteCardLeftButtonText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: '#484848',
  },
  qouteCardRightButtonText: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.whiteColor,
  },

  // PostedServiceCard.js
  postedServiceCardView: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
    alignItems: 'center',
  },
  postedServiceCardViewImage: {
    width: 70,
    height: 70,
    borderRadius: 70 / 2,
  },
  postedServiceCardViewText: {
    width: '78%',
    paddingLeft: 5,
  },
  postedServiceFeatureView: {
    marginBottom: 0,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 20,
    backgroundColor: Constant.greenColor,
  },
  postedServiceFeatureText: {
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.whiteColor,
  },
  postedServiceHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  postedServicePriceText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  postedServicePriceValue: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.blueColor,
  },
  postedServiceQueueText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  postedServiceQueueValue: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.secondryFontRegular,
    color: '#484848',
  },

  // AddonsServiceCard
  addonsServiceCardLeftButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomLeftRadius: 10,
    backgroundColor: Constant.grayColor,
  },
  addonsServiceCardRightButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomRightRadius: 10,
    backgroundColor: Constant.primaryColor,
    borderLeftColor: Constant.whiteColor,
  },
  addonsServiceCardLeftButtonText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: '#484848',
  },
  addonsServiceCardRightButtonText: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.whiteColor,
  },

  // ServiceStatusCard.js
  serviceStatusCardViewTile: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
    alignItems: 'center',
  },
  serviceStatusCardViewTileBottom: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 10,
    alignItems: 'center',
  },
  serviceStatusCardViewTileImage: {
    width: 55,
    height: 55,
    borderRadius: 55 / 2,
    borderWidth: 0.6,
    borderColor: Constant.borderColor,
  },
  serviceStatusCardViewTileHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  serviceStatusCardViewTilePriceText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  serviceStatusCardViewTilePriceValue: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.blueColor,
  },
  serviceStatusCardSeparatorView: {
    width: '15%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  serviceStatusCardRatingText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  serviceStatusCardRatingStars: {
    width: '30%',
    marginLeft: 10,
  },
  serviceStatusCardViewButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: Constant.grayColor,
  },
  serviceStatusCardViewButtonText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: '#484848',
  },

  // ServiceCancelStatusCard.js
  serviceCancelStatusCardView: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
    alignItems: 'center',
  },
  serviceCancelStatusCardViewBottom: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 10,
    alignItems: 'center',
  },
  serviceCancelStatusCardImage: {
    width: 70,
    height: 70,
    borderRadius: 70 / 2,
    borderColor: Constant.borderColor,
    borderWidth: 0.6,
  },
  serviceCancelStatusCardTextView: {
    width: '78%',
    paddingLeft: 5,
  },
  serviceCancelStatusCardFeature: {
    marginBottom: 0,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 20,
    backgroundColor: Constant.greenColor,
  },
  serviceCancelStatusCardFeatureText: {
    fontSize: 13,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.whiteColor,
  },
  serviceCancelStatusCardHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  serviceCancelStatusCardPrice: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  serviceCancelStatusCardPriceValue: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.blueColor,
  },
  serviceCancelStatusSeparator: {
    width: '20%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  serviceCancelStatusLeftButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomLeftRadius: 10,
    backgroundColor: Constant.grayColor,
  },
  serviceCancelStatusRightButton: {
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    borderColor: Constant.borderColor,
    borderWidth: 1,
    borderBottomRightRadius: 10,
    backgroundColor: Constant.primaryColor,
    borderLeftColor: Constant.whiteColor,
  },
  serviceCancelStatusLeftButtonText: {
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: '#484848',
  },
  serviceCancelStatusRightButtonText: {
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.whiteColor,
  },

  // ManageServices.js
  manageServicesRBSMainView: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
    marginTop: 15,
  },
  manageServicesRBSImage: {
    width: 55,
    height: 55,
    borderRadius: 55 / 2,
  },
  manageServicesRBSHeading: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  manageServicesRBSSubHeading: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  manageServicesRBSValues: {
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.blueColor,
  },
  manageServicesRBSSubCardTile: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 10,
  },
  manageServicesRBSDate: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.primaryFontSemiBold,
    color: Constant.fontColor,
  },
  manageServicesRBSValue: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    marginLeft: 15,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  manageServicesRBSReasonText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
    marginTop: 10,
    marginBottom: 5,
  },

  // InvoiceList.js
  invoiceListNotificationView: {
    backgroundColor: '#FFED99',
    padding: 15,
    borderRadius: 10,
    width: '100%',
  },
  invoiceListNotificationText: {
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0.5,
    fontFamily: Constant.primaryFontRegular,
    color: Constant.fontColor,
  },
  invoiceListCard: {
    borderColor: Constant.borderColor,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
  },
  invoiceListCardDataView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  invoiceListCardDataText: {
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontRegular,
    color: Constant.fontColor,
  },
  invoiceListCardDataValue: {
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: Constant.secondryFontSemiBold,
    color: Constant.fontColor,
  },
});
